### PR TITLE
Minutes from previous workshops

### PR DESCRIPTION
**Pull request by rgenoulaz**

### CODE REVIEW

**Comment by nissimsan** [comment]
Romain, I think you also had minutes from the Marseille meeting, didn't you? If yes, can you add those too? Apart from that good structure.

**Review by nissimsan — DISMISSED** [review]

**Comment by rgenoulaz** [comment]
OK I added minutes from two workshops in Marseille, and displayed the minutes as MD files.
hope you'll like it ;)

**Review by nissimsan — APPROVED** [review]
Perfect, thanks Romain

**Review by RababHayek — APPROVED** [review]

**Comment by nissimsan** [comment]
Thanks Romain - good minutes

**Pull request merged**
